version: '2.1'

services:
  telegrambotfriend:
    image: telegrambotfriend
    build: .
    environment:
      - BOT_FRIEND_TOKEN=TELEGRAM_TOKEN
      - BOT_FRIEND_LANGUAGE=TEXT_LANGUAGE
      - BOT_FRIEND_NAME=TELEGRAM_BOT_NAME
      - BOT_FRIEND_DROPBOX_ACCESS_TOKEN=DROPBOX_ACCESS_TOKEN
      - BOT_FRIEND_DROPBOX_FILE=DROPBOX_SOURCE_FILE
      - BOT_FRIEND_AUTO_FEED=BOT_AUTO_FEED
      - BOT_FRIEND_MEME_FILE=BOT_DROPBOX_MEME_FILE
